var age = 25;
age = true;
console.log(age);
age = 'hello';
console.log(age);
age = { name: 'Mkuru' };
console.log(age);
var mixed = [];
mixed.push(1);
mixed.push('mkuru');
mixed.push(false);
console.log(mixed);
var ninja;
ninja = { name: 'Mkuru', age: 34 };
console.log(ninja);
